// Code generated by hertz generator.

package auth

import (
	"context"
	"github.com/cloudwego/hertz/pkg/common/utils"
	"sheepim-api-gateway/biz/constant"
	"sheepim-api-gateway/biz/infra/container"

	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/protocol/consts"
	auth "sheepim-api-gateway/biz/model/auth"
)

// Login .
// @router /api/auth/login [POST]
func Login(ctx context.Context, c *app.RequestContext) {
	var err error
	var req auth.LoginReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.JSON(consts.StatusOK, utils.H{
			"code": constant.InvalidInput,
			"msg":  "参数校验失败:" + err.Error(),
		})
		return
	}

	App := container.GetGlobalContainer()
	resp, err := App.AuthService.Login(ctx, &req)
	c.JSON(consts.StatusOK, resp)
}
