// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package container

import (
	"github.com/li1553770945/sheepim-api-gateway/biz/infra/config"
	"github.com/li1553770945/sheepim-api-gateway/biz/infra/rpc"
	"github.com/li1553770945/sheepim-api-gateway/biz/internal/service/auth"
	"github.com/li1553770945/sheepim-api-gateway/biz/internal/service/user"
)

// Injectors from wire.go:

func GetContainer(config2 *config.Config) *Container {
	client := rpc.NewUserClient(config2)
	iUserService := user.NewUserService(client)
	authserviceClient := rpc.NewAuthClient(config2)
	iAuthService := auth.NewUserService(authserviceClient)
	container := NewContainer(config2, iUserService, iAuthService)
	return container
}
