// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package container

import (
	"sheepim-api-gateway/biz/infra/config"
	"sheepim-api-gateway/biz/infra/rpc"
	"sheepim-api-gateway/biz/internal/service/user"
)

// Injectors from wire.go:

func GetContainer(env string) *Container {
	configConfig := config.InitConfig(env)
	client := rpc.NewUserClient(configConfig)
	iUserService := user.NewUserService(client)
	container := NewContainer(configConfig, iUserService)
	return container
}
