// Code generated by hertz generator.

package room

import (
	"context"
	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/common/utils"
	"github.com/cloudwego/hertz/pkg/protocol/consts"
	"github.com/li1553770945/sheepim-api-gateway/biz/constant"
	"github.com/li1553770945/sheepim-api-gateway/biz/infra/container"
	room "github.com/li1553770945/sheepim-api-gateway/biz/model/room"
)

// CreateRoom .
// @router /api/rooms [POST]
func CreateRoom(ctx context.Context, c *app.RequestContext) {
	App := container.GetGlobalContainer()
	resp := App.RoomController.CreateRoom(ctx)
	c.JSON(consts.StatusOK, resp)
}

// JoinRoom .
// @router /api/rooms/join [POST]
func JoinRoom(ctx context.Context, c *app.RequestContext) {
	var err error
	var req room.JoinRoomReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.JSON(consts.StatusOK, utils.H{
			"code":    constant.InvalidInput,
			"message": "参数校验失败:" + err.Error(),
		})
		return
	}
	App := container.GetGlobalContainer()
	resp := App.RoomController.JoinRoom(ctx, &req)
	c.JSON(consts.StatusOK, resp)
}
