// Code generated by hertz generator.

package main

import (
	"context"
	"github.com/cloudwego/hertz/pkg/app/server"
	"github.com/cloudwego/hertz/pkg/common/hlog"
	"github.com/hertz-contrib/obs-opentelemetry/provider"
	hertztracing "github.com/hertz-contrib/obs-opentelemetry/tracing"
	"net"
	"os"
	configInfra "sheepim-api-gateway/biz/infra/config"
	"sheepim-api-gateway/biz/infra/container"
	"sheepim-api-gateway/biz/infra/log"
	"sheepim-api-gateway/biz/infra/trace"
)

func main() {
	env := os.Getenv("ENV")
	if env == "" {
		env = "development"
	}
	config := configInfra.GetConfig(env)
	//初始化日志
	log.InitLog()

	//初始化链路追踪

	p, tracer, cfg := trace.InitTrace(config)
	defer func(p provider.OtelProvider, ctx context.Context) {
		err := p.Shutdown(ctx)
		if err != nil {
			hlog.Fatalf("server stopped with error:%s", err)
		}
	}(p, context.Background())

	//初始化服务
	container.InitGlobalContainer(config)
	App := container.GetGlobalContainer()

	//初始化server
	addr, err := net.ResolveTCPAddr("tcp", App.Config.ServerConfig.ListenAddress)
	if err != nil {
		panic("设置监听地址出错")
	}

	h := server.Default(
		tracer,
		server.WithHostPorts(addr.String()),
	)

	h.Use(hertztracing.ServerMiddleware(cfg))

	register(h)
	h.Spin()
}
