// Code generated by hertz generator.

package project

import (
	"github.com/cloudwego/hertz/pkg/app"
)

func rootMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _apiMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _projectsMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getprojectsMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getprojectnumMw() []app.HandlerFunc {
	// your code...
	return nil
}
