// Code generated by hertz generator.

package room

import (
	"github.com/cloudwego/hertz/pkg/app"
	"github.com/li1553770945/sheepim-api-gateway/biz/middleware"
)

func rootMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _apiMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _roomsMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _createroomMw() []app.HandlerFunc {
	return []app.HandlerFunc{
		middleware.GetGlobalGlobalAuthMiddleware(), // 验证用户是否已登录
		middleware.AdminMiddleware(),               // 检查用户是否具有管理员权限
	}
}

func _joinroomMw() []app.HandlerFunc {
	// your code...
	return nil
}
