// Code generated by hertz generator.

package file

import (
	"context"
	"github.com/cloudwego/hertz/pkg/common/utils"
	"github.com/li1553770945/sheepim-api-gateway/biz/constant"
	"github.com/li1553770945/sheepim-api-gateway/biz/infra/container"

	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/protocol/consts"
	file "github.com/li1553770945/sheepim-api-gateway/biz/model/file"
)

// UploadFile .
// @router /api/file [POST]
func UploadFile(ctx context.Context, c *app.RequestContext) {
	var req file.UploadFileReq
	err := c.BindAndValidate(&req)
	if err != nil {
		c.JSON(consts.StatusOK, utils.H{
			"code": constant.InvalidInput,
			"msg":  "参数校验失败:" + err.Error(),
		})
		return
	}

	App := container.GetGlobalContainer()
	resp := App.FileController.UploadFile(ctx, &req)
	c.JSON(consts.StatusOK, resp)
}

// DownloadFileReq .
// @router /api/file [POST]
func DownloadFileReq(ctx context.Context, c *app.RequestContext) {
	var req file.DownloadFileReq
	err := c.BindAndValidate(&req)
	if err != nil {
		c.JSON(consts.StatusOK, utils.H{
			"code": constant.InvalidInput,
			"msg":  "参数校验失败:" + err.Error(),
		})
		return
	}

	App := container.GetGlobalContainer()
	resp := App.FileController.DownloadFile(ctx, &req)
	c.JSON(consts.StatusOK, resp)
}

// DeleteFile .
// @router /api/file [DELETE]
func DeleteFile(ctx context.Context, c *app.RequestContext) {
	var req file.DeleteFileReq
	err := c.BindAndValidate(&req)
	if err != nil {
		c.JSON(consts.StatusOK, utils.H{
			"code": constant.InvalidInput,
			"msg":  "参数校验失败:" + err.Error(),
		})
		return
	}

	App := container.GetGlobalContainer()
	resp := App.FileController.DeleteFile(ctx, &req)
	c.JSON(consts.StatusOK, resp)
}

// DownloadFile .
// @router /api/file [POST]
func DownloadFile(ctx context.Context, c *app.RequestContext) {
	var err error
	var req file.DownloadFileReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(file.DownloadFileResp)

	c.JSON(consts.StatusOK, resp)
}
