// Code generated by hertz generator.

package user

import (
	"context"
	"github.com/cloudwego/hertz/pkg/common/utils"
	"sheepim-api-gateway/biz/constant"
	"sheepim-api-gateway/biz/infra/container"

	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/protocol/consts"
	user "sheepim-api-gateway/biz/model/user"
)

// GetUserInfo .
// @router /user-info [GET]
func GetUserInfo(ctx context.Context, c *app.RequestContext) {
	var err error
	var req user.GetUserInfoReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.JSON(consts.StatusOK, utils.H{
			"code": constant.InvalidInput,
			"msg":  "参数校验失败:" + err.Error(),
		})
		return
	}
	App := container.GetGlobalContainer()
	resp, err := App.UserService.GetUserInfo(&req)
	c.JSON(consts.StatusOK, resp)
}
