// Code generated by hertz generator.

package aichat

import (
	"context"

	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/protocol/consts"
	"github.com/li1553770945/sheepim-api-gateway/biz/infra/container"
	aichat "github.com/li1553770945/sheepim-api-gateway/biz/model/aichat"
)

// SendMessage .
// @router /api/aichat [POST]
func SendMessage(ctx context.Context, c *app.RequestContext) {
	var err error
	var req aichat.AIChatReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	App := container.GetGlobalContainer()
	resp := App.AIChatController.SendMessage(ctx, &req, c)
	if resp == nil {
		return
	}
	c.JSON(consts.StatusOK, resp)
}
