// Code generated by hertz generator. DO NOT EDIT.

package router

import (
	"github.com/cloudwego/hertz/pkg/app/server"
	aichat "github.com/li1553770945/sheepim-api-gateway/biz/router/aichat"
	auth "github.com/li1553770945/sheepim-api-gateway/biz/router/auth"
	feedback "github.com/li1553770945/sheepim-api-gateway/biz/router/feedback"
	file "github.com/li1553770945/sheepim-api-gateway/biz/router/file"
	project "github.com/li1553770945/sheepim-api-gateway/biz/router/project"
	room "github.com/li1553770945/sheepim-api-gateway/biz/router/room"
	user "github.com/li1553770945/sheepim-api-gateway/biz/router/user"
)

// GeneratedRegister registers routers generated by IDL.
func GeneratedRegister(r *server.Hertz) {
	//INSERT_POINT: DO NOT DELETE THIS LINE!
	aichat.Register(r)

	file.Register(r)

	room.Register(r)

	feedback.Register(r)

	project.Register(r)

	auth.Register(r)

	user.Register(r)

}
